#!/usr/bin/env python
# -*- coding: utf-8 -*-
import hug
import requests
from bs4 import BeautifulSoup
import mysql.connector

db = mysql.connector.connect(host="127.0.0.1", user="root", database="Pokemon")
cursor = db.cursor()

    soup = BeautifulSoup(open(r"C:\Users\Yannick\Documents\poei_python\pokemon\pokemon_site.html"), "html.parser")
    tab = soup.find(id="pokedex")
    tt = []
    for link in tab.find_all("tr"):
        for l in link.find_all("td"):
            tt.append(l.text)


    print("INSERT INTO `pokedex`(`number`, `name`, `type`, `total`, `hp`, `attack`, `defense`, `sp.atk`, `sp.def`) VALUES(" + str(tt[0]) + str(tt[1]+")")